import { StyleSheet, Dimensions, Platform } from 'react-native';

const { width: SCREEN_WIDTH } = Dimensions.get('window');

export const getStyles = (theme: any, insets?: any) => {
  const T = theme.colors;
  return StyleSheet.create({
    container: { flex:1 },
    header: { flexDirection:'row', alignItems:'center', justifyContent:'space-between', paddingHorizontal:12, paddingVertical:10, borderBottomWidth:StyleSheet.hairlineWidth, borderBottomColor:T.bottomTabBorder },
    headerLeft: { flexDirection:'row', alignItems:'center', flex:1 },
    backBtn: { padding:4, marginRight:4 },
    avatarBorder: { width:42, height:42, borderRadius:21, borderWidth:2, justifyContent:'center', alignItems:'center', overflow:'hidden' },
    headerTitle: { fontSize:16, fontWeight:'700' },
    headerSub: { fontSize:12, marginTop:1 },
    headerRight: { flexDirection:'row', alignItems:'center', gap:14 },
    headerBtn: { padding:4 },
    searchBar: { flex:1, flexDirection:'row', alignItems:'center', backgroundColor:T.inputBackground, borderRadius:10, paddingHorizontal:6, borderWidth:1, borderColor:T.inputBorder },
    searchInput: { flex:1, height:38, fontSize:15, paddingHorizontal:6, color:T.inputText },
    toast: { position:'absolute', top:68, left:20, right:20, zIndex:999, flexDirection:'row', alignItems:'center', backgroundColor:T.cardBackground, paddingHorizontal:16, paddingVertical:10, borderRadius:20, borderWidth:StyleSheet.hairlineWidth, borderColor:'rgba(192,132,252,0.3)', alignSelf:'center' },
    toastText: { fontSize:13, fontWeight:'600' },
    datePillWrap: { alignItems:'center', marginVertical:10 },
    datePill: { paddingHorizontal:14, paddingVertical:5, borderRadius:12 },
    datePillText: { fontSize:11, fontWeight:'700', letterSpacing:0.5 },
    systemWrap: { alignItems:'center', marginVertical:4 },
    systemPill: { paddingHorizontal:14, paddingVertical:5, borderRadius:12 },
    systemText: { fontSize:12, fontWeight:'500', textAlign:'center' },
    swipeReplyAction: { justifyContent:'center', paddingLeft:14 },
    swipeReplyCircle: { width:34, height:34, borderRadius:17, backgroundColor:T.cardBackgroundLight, justifyContent:'center', alignItems:'center' },
    msgRow: { flexDirection:'row', marginBottom:3, paddingHorizontal:2 },
    msgRowMe: { justifyContent:'flex-end' },
    msgRowThem: { justifyContent:'flex-start' },
    bubble: { maxWidth:SCREEN_WIDTH*0.82, borderRadius:16, paddingHorizontal:10, paddingVertical:7, overflow:'hidden' },
    senderName: { fontSize:12, fontWeight:'700', marginBottom:3 },
    quoteBox: { borderLeftWidth:3, borderLeftColor:'rgba(192,132,252,0.7)', paddingLeft:8, paddingVertical:4, marginBottom:6, borderRadius:4, backgroundColor:T.cardBackgroundLight },
    quoteName: { fontSize:12, fontWeight:'700', marginBottom:2 },
    quoteText: { fontSize:12, lineHeight:17 },
    msgText: { fontSize:15, lineHeight:21 },
    tsAbsolute: { position:'absolute', bottom:-4, right:-6, flexDirection:'row', alignItems:'center' },
    tsOverlay: { position:'absolute', bottom:6, right:6, flexDirection:'row', alignItems:'center', backgroundColor:T.cardBackground, paddingHorizontal:5, paddingVertical:2, borderRadius:8 },
    tsText: { fontSize:11 },  deletedRow: { flexDirection:'row', alignItems:'center', opacity:0.75 },
    viewOnceBadge: { width:SCREEN_WIDTH*0.55, height:80, borderRadius:12, backgroundColor:'rgba(192,132,252,0.2)', borderWidth:1, borderColor:'rgba(192,132,252,0.4)', justifyContent:'center', alignItems:'center', gap:6 },
    viewOnceLabel: { color:theme.colors.textPrimary, fontSize:13, fontWeight:'600' },
    viewOnceViewed: { flexDirection:'row', alignItems:'center', paddingHorizontal:8, paddingVertical:10, opacity:0.6 },
    voiceContainer: { flexDirection:'row', alignItems:'center', paddingVertical:6, paddingHorizontal:2, width: SCREEN_WIDTH * 0.68, gap:8 },
    voicePlayBtn: { width:34, height:34, borderRadius:17, backgroundColor:T.cardBackgroundLight, justifyContent:'center', alignItems:'center' },
    voiceWaveArea: { flex:1 },
    voiceWaveTouch: { height:32, justifyContent:'center' },
    voiceWaveBars: { flexDirection:'row', alignItems:'center', height:32, gap:1.5 },
    voiceBar: { width:2.5, borderRadius:2 },
    voiceMetaRow: { flexDirection:'row', alignItems:'center', marginTop:3 },
    voiceProgressTrack: { height: 2, backgroundColor: theme.colors.cardBackgroundLight, borderRadius: 1, marginTop: 4, marginBottom: 2, overflow: 'hidden' },
    voiceProgressFill: { height: '100%', borderRadius: 1 },
    liveWaveContainer: { flex:1, flexDirection:'row', alignItems:'center', height:32, gap:1.5 },
    liveWaveBar: { width:2.5, borderRadius:2, backgroundColor: '#ef4444' },
    reactionPillRow: { flexDirection:'row', marginTop:2, marginBottom:4 },
    reactionPill: { flexDirection:'row', alignItems:'center', backgroundColor:T.reactionPill, borderWidth:1, borderColor:'rgba(192,132,252,0.35)', borderRadius:12, paddingHorizontal:8, paddingVertical:3, gap:3 },
    reactionPillText: { fontSize:14 },
    reactionCount: { fontSize:12, color:T.textMuted },
    tsBubbleRow: { flexDirection:'row', alignItems:'flex-end', marginLeft:6, marginBottom:1, alignSelf:'flex-end' },
    readMoreRow: { flexDirection:'row', alignItems:'center', marginTop:4, paddingTop:2 },
    readMoreText: { fontSize:13, fontWeight:'600' },
    contextBar: { flexDirection:'row', alignItems:'center', paddingHorizontal:14, paddingVertical:10, borderLeftWidth:4, borderTopWidth:StyleSheet.hairlineWidth, borderTopColor:T.bottomTabBorder },
    contextName: { fontSize:13, fontWeight:'700', marginBottom:2 },
    contextText: { fontSize:12 },
    inputDeck: { flexDirection:'row', alignItems:'center', paddingHorizontal:8, paddingVertical:8, gap:6 },
    plusBtn: { padding:4 },
    inputBox: { flex:1, flexDirection:'row', alignItems:'center', borderRadius:22, paddingHorizontal:12, minHeight:42 },
    inputField: { flex:1, fontSize:15, paddingVertical:8, maxHeight:110 },
    rightBtns: { flexDirection:'row', alignItems:'center', gap:6 },
    iconBtn: { padding:4 },
    sendBtn: { width:42, height:42, borderRadius:21, justifyContent:'center', alignItems:'center' },
    overlay: { flex:1, backgroundColor:'rgba(0,0,0,0.55)', justifyContent:'center', alignItems:'center' },
    sheetOverlay: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(0,0,0,0.6)' },
    actionSheet: {
      position: 'absolute', bottom: 0, left: 0, right: 0,
      backgroundColor: theme.colors.bottomTabBackground,   // #2a0c4f — matches app bottom tab
      borderTopLeftRadius: 22, borderTopRightRadius: 22,
      paddingTop: 10, paddingHorizontal: 20,
      paddingBottom: Math.max(Platform.OS === 'android' ? 36 : 24, (insets?.bottom || 0) + (Platform.OS === 'android' ? 32 : 16)),
      borderTopWidth: 1, borderColor: theme.colors.bottomTabBorder,
      shadowColor: theme.colors.background, shadowOffset: { width:0, height:-6 },
      shadowOpacity: 0.5, shadowRadius: 20, elevation: 24,
    },
    sheetHandle: {
      width: 40, height: 4, borderRadius: 2,
      backgroundColor: theme.colors.bottomTabBorder,
      alignSelf: 'center', marginBottom: 18,
    },
    sheetDivider: {
      height: StyleSheet.hairlineWidth,
      backgroundColor: theme.colors.bottomTabBorder,
      marginVertical: 6, marginHorizontal: -20,
    },
    reactionRow: {
      flexDirection: 'row', justifyContent: 'space-between',
      paddingHorizontal: 0, paddingVertical: 4, marginBottom: 4,
    },
    reactionBtn: {
      alignItems: 'center', justifyContent: 'center',
      width: Math.floor((SCREEN_WIDTH - 40) / 8) - 2,
      height: Math.floor((SCREEN_WIDTH - 40) / 8) - 2,
      borderRadius: Math.floor((SCREEN_WIDTH - 40) / 16),
      backgroundColor: theme.colors.cardBackground,
    },
    reactionBtnActive: {
      backgroundColor: 'rgba(192,132,252,0.18)',
      borderWidth: 2,
      borderColor: theme.colors.accent,
    },
    reactionEmoji: { fontSize: Math.min(26, Math.floor((SCREEN_WIDTH - 40) / 8) * 0.52) },
    reactionDot: { width: 5, height: 5, borderRadius: 3, backgroundColor: theme.colors.accent, marginTop: 2 },
    actionItem: {
      flexDirection: 'row', alignItems: 'center',
      paddingVertical: 13, gap: 16,
    },
    actionIconWrap: {
      width: 40, height: 40, borderRadius: 20,
      backgroundColor: theme.colors.cardBackground,
      justifyContent: 'center', alignItems: 'center',
    },
    actionText: { fontSize: 16, fontWeight: '500', color: theme.colors.textPrimary },
    imgViewerBtn: { padding:8, backgroundColor:'rgba(0,0,0,0.5)', borderRadius:20 },
    attachMenu: { width:SCREEN_WIDTH*0.9, borderRadius:18, padding:24, marginBottom:90, marginTop:'auto', alignSelf:'center' },
    attachRow: { flexDirection:'row', justifyContent:'space-around', flexWrap:'wrap', gap:16 },
    attachBtn: { alignItems:'center', width:68 },
    attachIcon: { width:58, height:58, borderRadius:29, justifyContent:'center', alignItems:'center', marginBottom:7 },
    attachLabel: { color: theme.colors.textPrimary, fontSize:12 },
    songShareCard: { width: SCREEN_WIDTH * 0.72, borderRadius: 12, overflow: 'hidden', backgroundColor: T.cardBackgroundLight, borderWidth: 1, borderColor: T.bottomTabBorder },
    songShareHeader: { flexDirection: 'row', alignItems: 'center', gap: 5, paddingHorizontal: 10, paddingTop: 8, paddingBottom: 4 },
    songShareLabel: { fontSize: 10, fontWeight: '700', color: T.accent, textTransform: 'uppercase', letterSpacing: 0.8 },
    songShareBody: { flexDirection: 'row', alignItems: 'flex-start', paddingHorizontal: 10, paddingBottom: 8, gap: 10 },
    songShareIconWrap: { width: 40, height: 40, borderRadius: 8, backgroundColor: T.cardBackgroundLight, justifyContent: 'center', alignItems: 'center', marginTop: 2 },
    songShareTitle: { fontSize: 14, fontWeight: '700', color: T.textPrimary, marginBottom: 2 },
    songShareSub: { fontSize: 12, color: T.accent, fontWeight: '600', marginBottom: 1 },
    songShareProg: { fontSize: 11, color: T.textSecondary, marginBottom: 4 },
    songShareTag: { flexDirection: 'row', alignItems: 'center', gap: 3, backgroundColor: T.cardBackgroundLight, borderWidth: 1, borderColor: T.bottomTabBorder, borderRadius: 6, paddingHorizontal: 6, paddingVertical: 2 },
    songShareTagText: { fontSize: 10, color: T.textPrimary, fontWeight: '600' },
    songSharePlayRow: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingHorizontal: 10, paddingVertical: 8, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: T.bottomTabBorder },
    songSharePlayText: { fontSize: 12, color: T.textSecondary, flex: 1 },
    songShareNote: { paddingHorizontal: 10, paddingBottom: 8, paddingTop: 2 },
    songShareNoteText: { fontSize: 13, color: T.textSecondary, fontStyle: 'italic', lineHeight: 18 },
    docCard: { flexDirection: 'row', alignItems: 'center', gap: 10, padding: 10, width: SCREEN_WIDTH * 0.65 },
    docIconWrap: { width: 40, height: 40, borderRadius: 8, backgroundColor: 'rgba(192,132,252,0.15)', justifyContent: 'center', alignItems: 'center' },
    forwardedLabel: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      marginBottom: 3,
      opacity: 0.7,
    },
    forwardedText: {
      color: T.textMuted,
      fontSize: 11,
      fontStyle: 'italic',
    },
    pinnedBanner: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 16,
      paddingVertical: 8,
      zIndex: 10,
    },
    pinnedBannerTitle: {
      fontSize: 11,
      fontWeight: '700',
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    pinnedBannerText: {
      fontSize: 13,
      marginTop: 1,
    },
    modalHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      paddingVertical: 12,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.colors.bottomTabBorder,
    },
    modalCloseBtn: {
      padding: 4,
    },
    modalTitle: {
      fontSize: 17,
      fontWeight: '700',
      color: theme.colors.textPrimary,
    },
    modalTabs: {
      flexDirection: 'row',
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.colors.bottomTabBorder,
    },
    modalTab: {
      flex: 1,
      alignItems: 'center',
      paddingVertical: 12,
      borderBottomWidth: 2,
      borderBottomColor: 'transparent',
    },
    modalTabActive: {
      borderBottomColor: theme.colors.accent,
    },
    modalTabText: {
      fontSize: 14,
      fontWeight: '600',
      color: theme.colors.textMuted,
    },
    modalTabTextActive: {
      color: theme.colors.textPrimary,
    },
    modalMsgCard: {
      backgroundColor: T.cardBackgroundLight,
      borderWidth: 1,
      borderColor: theme.colors.bottomTabBorder,
      borderRadius: 12,
      padding: 12,
      marginBottom: 12,
    },
    modalMsgHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 4,
    },
    modalMsgSender: {
      fontSize: 13,
      fontWeight: '700',
    },
    modalMsgFooter: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
      marginTop: 8,
      paddingTop: 8,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: theme.colors.bottomTabBorder,
    },
    modalMsgAction: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      paddingVertical: 4,
      paddingHorizontal: 8,
    },
    flatList: {
      flex: 1,
    },
  });
};
